- hosts: all
  gather_facts: no

  tasks: 

  - yum: name=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm  state=present
 
  - name: install dependencies 
    yum: pkg={{item}} state=installed
    with_items:
     - python-pip
     - git
     - python-devel
     - gcc
     - gcc-c++

  - git: repo=https://github.com/ethereum/pyethereum.git dest=/tmp/pyethereum

  - pip: requirements=/tmp/pyethereum/requirements.txt

